#ifndef IMAGEPICKERLIBRARY_GLOBAL_H
#define IMAGEPICKERLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IMAGEPICKERLIBRARY_LIBRARY)
#  define IMAGEPICKERLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define IMAGEPICKERLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGEPICKERLIBRARY_GLOBAL_H
